Adds NUM_TIMES_SAMPLED agent metadata to the submitted profile
aws/amazon-codeguru-profiler-python-agent pull request #34
Opened 2021-05-12 19:20 UTC by ysshao96

*Description of changes:*
Adds serialization logic to submit `total_sample_count` as  NUM_TIMES_SAMPLED property of the AgentMetadata.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-05-12 19:47 UTC, pandpara reviewed
Can you update the minimum samples in a profile to 1 to make it consistent with java agent : https://github.com/aws/amazon-codeguru-profiler-python-agent/blob/main/codeguru_profiler_agent/profiler_disabler.py#L9

2021-05-14 16:29 UTC, mirelap-amazon commented on codeguru_profiler_agent/profiler_disabler.py
> +MINIMUM_SAMPLES_IN_PROFILE = 1
I know you got this as a comment from @pandpara , but I don't think this should be updated, and especially in this commit. This affects if the profiler is disabled or not and it's different than what the general message of this commit is about. If there's a concern about this value, we can do it in a different commit (even release).

2021-05-14 16:29 UTC, mirelap-amazon requested changes
One comment about the MINIMUM_SAMPLES_IN_PROFILE

2021-05-14 17:03 UTC, mirelap-amazon approved these changes

2021-05-14 20:33 UTC, merged

2021-05-14 21:01 UTC, Shay-Jin commented
Hi Max, could you have a `numTimesSampled > 0` check before submitting profiles?